version: '3'
services:
# docker-compose exec db bash
# psql -h 127.0.0.1 -p 5432 -U default_user -W default_db
  db:
    image: postgres:latest
    container_name: postgresql-learn
    ports:
      - 5432:5432
    volumes:
      - ./postgres/init:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_INITDB_ARGS="--encoding=UTF-8"
    hostname: postgres
    restart: always
  nginx:
    image: nginx:latest
    container_name: nginx-learn
    ports:
      - "80:80"
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
